### ISSUE TITLE
Erro ao invocar o ffmpeg

### ISSUE THREAD

**Issue by daltonserey** [diego-aquino/mediakit#42]
Oi Diego, segue uma falha que ocorreu quando mostrei para alguns alunos com o link de um vídeo escolhido por eles.

```
$ mediakit https://www.youtube.com/watch?v=DvKAPAmGPas o.mp4
mediakit v0.5.3

info Ready to download cachorrinho a a folou (... [360p]
info Total download size: 0.7 MB

? Confirm download? (Y/n) 
⠙ Converting cachorrinho a a folou (... [360p]

  █████████████████████████████████████████████████████ 100.0% (0.7 MB / 0.7 MB)

error Something went wrong. :(
Please, try again.

Traceback (most recent call last):
  File "/home/dalton/mk/bin/mediakit", line 8, in <module>
    sys.exit(main())
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/main.py", line 6, in main
    action()
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/actions/download.py", line 109, in download
    raise exception
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/actions/download.py", line 91, in download
    download_cli.download_selected_formats()
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/streams/cli.py", line 213, in download_selected_formats
    media_resource.download()
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/media/download.py", line 111, in download
    self._convert_dowloaded_resources()
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/media/download.py", line 132, in _convert_dowloaded_resources
    self._convert_downloaded_video()
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/media/download.py", line 174, in _convert_downloaded_video
    convert_media(
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/media/convert.py", line 43, in convert_media
    run_command_in_background(command)
  File "/home/dalton/mk/lib/python3.8/site-packages/mediakit/utils/commands.py", line 8, in run_command_in_background
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ffmpeg -i "/home/dalton/mediakit_temp[video].mp4" -vcodec copy -f mp4 "/home/dalton/o.mp4" ' returned non-zero exit status 1.
(mk) [dalton@dell2 ~]
```

**Comment by diego-aquino** [comment]
Oi, @daltonserey. Poderia atualizar para a versão 0.5.4.dev0 e tentar novamente?
```bash
$ pip install mediakit==0.5.4.dev0
```
