### ISSUE TITLE
Any clue ?

### ISSUE THREAD

**Issue by sajati** [diego-aquino/mediakit#56]
```
user@ARM:/media/EXTERNAL_HDD/Videos# mediakit https://www.youtube.com/watch?v=N84yBEsSiVs -f 4K
mediakit v0.7.1

info Loading video..

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mediakit/cli/download/download_cli.py", line 406, in load_video
    videos_data[video_index] = self._load_video_data(
  File "/usr/local/lib/python3.8/dist-packages/mediakit/cli/download/download_cli.py", line 422, in _load_video_data
    available_formats = self._get_available_formats(video)
  File "/usr/local/lib/python3.8/dist-packages/mediakit/cli/download/download_cli.py", line 438, in _get_available_formats
    video_streams = video.streams.filter(type="video")
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'
error Something went wrong. :(
Traceback (most recent call last):
  File "/usr/local/bin/mediakit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mediakit/main.py", line 6, in main
    action()
  File "/usr/local/lib/python3.8/dist-packages/mediakit/actions/download.py", line 72, in download
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/mediakit/actions/download.py", line 53, in download
    download_cli.start(video_urls_to_download, arguments.formats)
  File "/usr/local/lib/python3.8/dist-packages/mediakit/cli/download/download_cli.py", line 44, in start
    self._register_videos_to_download(video_urls_to_download, formats)
  File "/usr/local/lib/python3.8/dist-packages/mediakit/cli/download/download_cli.py", line 75, in _register_videos_to_download
    for (
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by diego-aquino** [comment]
@sajati, this seems to be a problem with [pytube](https://github.com/pytube/pytube), one of the libraries Mediakit uses internally. [This issue](https://github.com/pytube/pytube/issues/1326) references the bug. 

Unfortunately, this project is no longer maintained and will be archived soon. Pytube requires constant fixes and Mediakit is frequently broken while they are not resolved.

There are alternatives to Mediakit, including many more features and contributors. My personal recommendations are [youtube-dl](https://github.com/ytdl-org/youtube-dl) and [yt-dlp](https://github.com/yt-dlp/yt-dlp) (I like yt-dlp as it usually provides higher download speeds).
